version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  trigger-tests: mabl/trigger-tests@1.0.8

workflows:
  my_workflow_for_nodetodo:
    jobs:
      - build_web
      - test_web:
          requires:
            - build_web
      - release_image:
          context: aws
          requires:
            - test_web
      - run_mabl_tests:
          requires:
            - release_image

jobs:
  build_web:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules/*
  test_web:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          command: mkdir reports
      - run:
          command: npx eslint . --ext .js --format junit --output-file ./reports/eslint/eslint.xml
      - store_test_results:
          path: ./reports
  release_image:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - aws-ecr/build-and-push-image:
          create-repo: true
          setup-remote-docker: true
          remote-docker-layer-caching: true
          repo: cci-nodetodo
  run_mabl_tests:
    machine: true
    steps:
      - trigger-tests/run-tests:
          application-id: naMfa4ho96G0Al0ccA8KcA-a
          environment-id: Ba4jXgdJPoZdWrfPEzAFBw-e
      - trigger-tests/parse-results
      - store_test_results:
          path: ./test-results
