version: 2.1

orbs:
  node: circleci/node@4.2.3
  cloud-run: circleci/gcp-cloud-run@1.0.2
  trigger-tests: mabl/trigger-tests@1.0.8

workflows:
  my_workflow_for_nodetodo:
    jobs:
      - build_web
      - test_web:
          requires:
            - build_web
#      - release_web:
#          requires:
#            - test_web
#      - deploy_web:
#          requires:
#            - release_web
#      - run_mabl_tests:
#          requires:
#            - deploy_web

jobs:
  build_web:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules/*
  test_web:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          command: mkdir reports
      - run:
          command: npx eslint . --ext .js --format junit --output-file ./reports/eslint/eslint.xml
      - store_test_results:
          path: ./reports
  release_web:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - cloud-run/init
      - cloud-run/build:
          tag: "gcr.io/${GOOGLE_PROJECT_ID}/nodetodo-${CIRCLE_SHA1}"
  deploy_web:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - cloud-run/init
      - cloud-run/deploy:
          image: "gcr.io/${GOOGLE_PROJECT_ID}/nodetodo-${CIRCLE_SHA1}"
          platform: managed
          region: us-central1
          service-name: nodetodo
          unauthenticated: true
  run_mabl_tests:
    machine: true
    steps:
      - trigger-tests/run-tests:
          application-id: qG8IvB1fl9qIsB9RTh5jnw-a
      - trigger-tests/parse-results
      - store_test_results:
          path: ./test-results
